### ISSUE TITLE
Loopback fails on android

### ISSUE THREAD

**Issue by rafasimao** [UnBiquitous/uos_core#10]
When trying to register one class in a driver into the same device running android, we get an null pointer exception. The exactly point where it gets the exception is in the
MessageHandler class, line 155, send method, command "OutputStream outputStream = connection.getDataOutputStream();". This happens because the previous command gets a null connection, which happens because of a refused connection that happens in the EthernetTCPClientConnection, line 56, command "this.tcpSocket = new Socket(host, port);".

**Comment by nuk** [comment]
Fixed on branch #1 .
See if it fixes.

**Comment by nuk** [comment]
According to @rafasimao its working now
