### ISSUE TITLE
Increasing thread number - lag

### ISSUE THREAD

**Issue by rafasimao** [UnBiquitous/uos_core#17]
While sending many uosevents the number of threads increase causing lag.
![captura de tela 2013-07-25 as 1 00 30 pm](https://f.cloud.github.com/assets/2564038/856782/8e34a638-f543-11e2-9c65-87fd606cab8b.png)

**Comment by nuk** [comment]
This problem was related with the Socket-Plugin so was fixed on commit UnBiquitous/uos_socket_plugin/1e81d0b8fa68ef084a1a4cb4555462aa5240a8a3

**Comment by rafasimao** [comment]
[image: Imagem inline 1]

2013/7/26 Fabricio Buzeto notifications@github.com

> This problem was related with the Socket-Plugin so was fixed on commit
> 1e81d0bhttps://github.com/UnBiquitous/uos_core/commit/1e81d0b8fa68ef084a1a4cb4555462aa5240a8a3
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/UnBiquitous/uos_core/issues/17#issuecomment-21629721
> .

## 

---

Rafael Simão
(61) 9623-4345

**Comment by nuk** [comment]
No image came

**Comment by rafasimao** [comment]
[image: Imagem inline 1]

2013/7/28 Fabricio Buzeto notifications@github.com

> No image came
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/UnBiquitous/uos_core/issues/17#issuecomment-21683862
> .

## 

---

Rafael Simão
(61) 9623-4345

**Comment by nuk** [comment]
Qhen you send the image on the email, the image is not attached =[

**Comment by nuk** [comment]
Version #1 fixed this issue.
