### ISSUE TITLE
Get UpDevice object from the CallContext parameter

### ISSUE THREAD

**Issue by matheuscscp** [UnBiquitous/uos_core#20]
Inside a service call, we can get the caller device name and search the associated UpDevice object using the Gateway. It would be nice if we could get the associated UpDevice object from the CallContext parameter of a service call, so we could more easily make response service calls.

**Comment by nuk** [comment]
Now we have two properties, one named `callerDevice:UpDevice` and one `callerNetworkDevice:networkDevice` to handle this.
