### ISSUE TITLE
Event notification

### ISSUE THREAD

**Issue by matheuscscp** [UnBiquitous/uos_core#22]
To send event notifications, we have to register an UpDevice inside an UosEventDriver and call gateway.sendEventNotify() passing this UpDevice. The middleware inside this device will only notify listeners to "notify.eventKey", okay. But sometimes the event notification can be assigned to only one listener, like a message and not an event. One solution would be to send a parameter to identify the listener and the implementations of "listener.handleNotify ()" should check if the event is for this listener. But that would be a little insecure, because the implementation might try to take advantage of this need and simply do not check. I think that the event manager needs to implement this support of events for specific listeners.

**Comment by nuk** [comment]
Sorry, but the suggestion (or problem) is not clear to me.

**Comment by nuk** [comment]
Talking with ya I can see that you're worried on how to handle multiple simultaneous registers for the same driver. Or even for the same event on that driver.

I think this issue can be handled nicely by the driver programmer on the `registerForEvent` without needing any help by the middleware. Of course we can improve the rules of how to manage service calls, but I don't think it fits the lightweight intent of the middleware for now.
