### ISSUE TITLE
Problema de handshake com Mac

### ISSUE THREAD

**Issue by viniciusln** [UnBiquitous/uos_core#36]
Problema ao tentar fazer handshake entre dispositivos na rede utilizando MAC.

Segue o log:

INFO -[1.0](org.unbiquitous.uos.core.UOS.init) : ..::|| Starting uOS ||::..
INFO -[1.1](org.unbiquitous.uos.network.socket.connectionManager.TCPConnectionManager.setProperties) : No Alternative TCP Port defined
FINE -[9.2](org.unbiquitous.uos.network.socket.connectionManager.TCPConnectionManager.run) : Starting UbiquitOS Smart-Space Ethernet TCP Connection Manager.
INFO -[9.3](org.unbiquitous.uos.network.socket.connectionManager.TCPConnectionManager.run) : Starting Ethernet TCP Connection Manager...
SEVERE -[1.4](org.unbiquitous.uos.core.network.radar.RadarControlCenter.loadRadars) : Error reading UbiquitOS Resource Bundle Propertie File. Check if the files exists or there is no errors in his definitions. The found error is: null
INFO -[9.5](org.unbiquitous.uos.network.socket.connectionManager.TCPConnectionManager.run) : Ethernet TCP Connection Manager is started.
FINE -[1.6](org.unbiquitous.uos.network.socket.connectionManager.TCPConnectionManager.getNetworkDevice) : returning:org.unbiquitous.uos.network.socket.SocketDevice@2f92e0f4
INFO -[1.7](org.unbiquitous.uos.core.CurrentDeviceInitializer.init) : Ethernet:TCP > 192.168.0.45:14984
FINE -[1.8](org.unbiquitous.uos.core.SecurityManager.loadAuthenticationHandlers) : No ubiquitos.security.authenticationHandlerList specified.
FINE -[1.9](org.unbiquitous.uos.core.SecurityManager.loadTranslationHandlers) : No ubiquitos.security.translationHandlerList specified.
INFO -[1.10](org.unbiquitous.uos.core.driverManager.DriverDeployer.deployDrivers) : Deploying Drivers.
WARNING -[1.11](org.unbiquitous.uos.core.driverManager.DriverDeployer.deployDrivers) : No 'ubiquitos.driver.deploylist' property defined. This implies on no drivers for this instance.
INFO -[1.12](org.unbiquitous.uos.core.applicationManager.ApplicationDeployer.deployApplications) : Iniatialize Application Deploy.
INFO -[1.13](org.unbiquitous.uos.core.applicationManager.ApplicationDeployer.deployApplication) : Deploying Application ConsoleApp
FINE -[1.14](org.unbiquitous.uos.core.driverManager.DriverManager.deployDriver) : Deployed Driver : uos.DeviceDriver with id uos.DeviceDriver1
FINE -[1.15](org.unbiquitous.uos.core.driverManager.DriverManager.initDrivers) : Initializing 1 drivers.
FINE -[1.16](org.unbiquitous.uos.core.driverManager.DriverManager.initDrivers) : Initialized Driver uos.DeviceDriver with id 'uos.DeviceDriver1'
INFO -[1.17](org.unbiquitous.uos.core.connectivity.ConnectivityManager.init) : Starting up UOS Connectivity Manager
FINE -[1.18](org.unbiquitous.uos.core.connectivity.ConnectivityManager.init) : DoProxying? false
INFO -[1.19](org.unbiquitous.uos.core.connectivity.ConnectivityManager.init) : Connectivity Manager is started
INFO -[11.20](org.unbiquitous.uos.network.socket.radar.MulticastRadar.handleBeacon) : Entered device 192.168.0.45.
FINE -[11.21](org.unbiquitous.uos.core.deviceManager.DeviceManager.deviceEntered) : Host of device entered is the same of current device:192.168.0.45:14984
INFO -[11.22](org.unbiquitous.uos.network.socket.radar.MulticastRadar.handleBeacon) : Entered device 192.168.0.30.
FINE -[11.23](org.unbiquitous.uos.core.deviceManager.DeviceManager.retrieveDevice) : No device found with addr '192.168.0.30' on network 'Ethernet:TCP'.
FINE -[11.24](org.unbiquitous.uos.core.deviceManager.DeviceManager.doHandshake) : Trying to hanshake with device : 192.168.0.30:14984
FINE -[11.25](org.unbiquitous.uos.network.socket.connectionManager.TCPConnectionManager.getNetworkDevice) : returning:org.unbiquitous.uos.network.socket.SocketDevice@2f92e0f4
SEVERE -[11.26](org.unbiquitous.uos.core.deviceManager.DeviceManager.doHandshake) : Not possible to handshake with device '192.168.0.30:14984'. org.unbiquitous.uos.core.messageEngine.MessageEngineException: java.lang.NullPointerException
INFO -[11.27](org.unbiquitous.uos.network.socket.radar.MulticastRadar.handleBeacon) : Entered device 192.168.0.45.
FINE -[11.28](org.unbiquitous.uos.core.deviceManager.DeviceManager.deviceEntered) : Host of device entered is the same of current device:192.168.0.45:14984

**Comment by nuk** [comment]
Can we consider it solved?

**Comment by viniciusln** [comment]
Yes, it's ok now!
