### ISSUE TITLE
Problema de handshake após loop do MulticastRadar

### ISSUE THREAD

**Issue by viniciusln** [UnBiquitous/uos_core#44]
Está acontecendo um problema no uOS core onde o HandShake falha após a segunda passada do MulticastRadar. O primeiro handshake acontece normalmente, e após a segunda passada do radar, o handshake falha.

**Comment by nuk** [comment]
I think the last PR fixes it.

**Comment by nuk** [comment]
Don't forget to update the uos-socket also
